<?php

define('ERREUR_EMAIL', 1);
define('ERREUR_CHAMP_VIDE', 2);
define('PASSWORD_PAS_IDENTIQUE', 3);
define('ERREUR_PASSWORD_LENGTH', 4);
define('ERREUR_ENREGISTREMENT', 5);
define('ERREUR_WRONG_PASSWORD', 6);
define('ERREUR_DE_CONNECTION', 7);
define('ERREUR_TELEPHONE', 8);